from setuptools import setup, find_packages

setup(
    name="statmodkit",
    version="0.1.0",
    packages=find_packages(),
    install_requires=[
        "numpy>=1.21.0",
        "pandas>=1.3.0",
        "scikit-learn>=1.0.0",
        "statsmodels>=0.13.0",
        "matplotlib>=3.4.0",
        "seaborn>=0.11.0",
        "optuna>=2.10.0",
        "mlxtend>=0.19.0",
        "xgboost>=1.5.0",
        "lightgbm>=3.3.0",
        "catboost>=1.0.0",
        "joblib>=1.1.0",
        "dask>=2022.2.0",
        "dask-ml>=1.9.0",
        "python-Levenshtein>=0.12.0",
    ],
    author="Your Name",
    author_email="your.email@example.com",
    description="A comprehensive statistical modeling toolkit with advanced feature engineering and model selection capabilities",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/yourusername/statmodkit",
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Science/Research",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
    ],
    python_requires=">=3.8",
) 